const authors = [
  "Thomas Edison",
  "Yogi Berra",
  "Abraham Lincoln",
  "Johann Wolfgang von Goethe",
  "Byron Pulsifer",
  "Lao Tzu",
  "Carl Sandburg",
  "Aristotle",
  "Margaret Sangster",
  "Buddha",
  "Iris Murdoch",
  "Karen Clark",
  "Wayne Dyer",
  "William Shakespeare",
  "Henry J. Kaiser",
  "Publilius Syrus",
  "Napoleon Hill",
  "Donald Trump",
  "Benjamin Spock",
  "Confucius",
  "Sigmund Freud",
  "Benjamin Franklin",
  "Ella Williams",
  "Christopher Reeve",
  "Albert Einstein",
  "Charles Kettering",
  "Chinese proverb",
  "Socrates",
  "V. Naipaul",
  "John Wooden",
  "Haddon Robinson",
  "Pearl Buck",
  "Brian Tracy",
  "Leonardo da Vinci",
  "Dalai Lama",
  "Larry Elder",
  "Michael Korda",
  "James Lowell",
  "Yoda",
  "Harriet Beecher Stowe",
  "Murray Gell-Mann",
  "John Lennon",
  "Pericles",
  "Baltasar Gracian",
  "Cullen Hightower",
  "African proverb",
  "Ralph Emerson",
  "Sophocles",
  "Maya Angelou",
  "Richard Evans",
  "Bodhidharma",
  "Michelangelo",
  "Winston Churchill",
  "Leo Tolstoy",
  "Princess Diana",
  "John Pierrakos",
  "Eleanor Roosevelt",
  "Richard Bach",
  "Seneca",
  "Napoleon Bonaparte",
  "Bo Jackson",
  "Thich Nhat Hanh",
  "Liberace",
  "William Arthur Ward",
  "Ellen Gilchrist",
  "Albert Schweitzer",
  "Carl Jung",
  "Lord Herbert",
  "Anne Wilson Schaef",
  "Sojourner Truth",
  "Elizabeth Browning",
  "German proverb",
  "Madame de Stael",
  "Bernadette Devlin",
  "Walt Disney",
  "Anais Nin",
  "Sun Tzu",
  "American proverb",
  "Jon Kabat-Zinn",
  "Gustave Flaubert",
  "Sylvia Voirol",
  "Theophrastus",
  "Tony Robbins",
  "Oscar Wilde",
  "Gloria Steinem",
  "Marcus Aurelius",
  "Bernard Shaw",
  "Mary Bethune",
  "Pablo Picasso",
  "Usman Asif",
  "Victor Hugo",
  "Epictetus",
  "Robert Heller",
  "Plutarch",
  "Ralph Waldo Emerson",
  "Mahatma Gandhi",
  "Wit",
  "Voltaire",
  "Virgil",
  "Joseph Stalin",
  "Robert Frost",
  "Thomas Fuller",
  "Elbert Hubbard",
  "Turkish proverb",
  "Hugh Miller",
  "A. Powell Davies",
  "John Dryden",
  "Friedrich von Schiller",
  "Mike Ditka",
  "Immanuel Kant",
  "Albert Camus",
  "Toni Morrison",
  "Helen Keller",
  "Paulo Coelho",
  "Jonathan Kozol",
  "Janis Joplin",
  "Honore de Balzac",
  "Ovid",
  "Francis Bacon",
  "Manuel Puig",
  "William R. Inge",
  "Jim Rohn",
  "Oprah Winfrey",
  "Anatole France",
  "Saint Augustine",
  "Maya Lin",
  "Blaise Pascal",
  "Jonas Salk",
  "Peter Drucker",
  "Luisa Sigea",
  "Dr. Seuss",
  "Jason Fried",
  "Babe Ruth",
  "Carlyle",
  "Leo F. Buscaglia",
  "Indira Gandhi",
  "Plato",
  "Frederick Douglass",
  "Willa Cather",
  "Jean de la Fontaine",
  "Thomas Jefferson",
  "Thomas Dewar",
  "George Patton",
  "Benjamin Disraeli",
  "Horace Friess",
  "Haynes Bayly",
  "Lauren Bacall",
  "Frank Herbert",
  "Arthur Conan Doyle",
  "J. Willard Marriott",
  "Edward Gibbon",
  "Og Mandino",
  "Lewis B. Smedes",
  "Nikos Kazantzakis",
  "John Eliot",
  "A. A. Milne",
  "Marie Curie",
  "Lawrence Peter",
  "Hannah More",
  "John Berry",
  "William Yeats",
  "Ken S. Keyes",
  "Anne Schaef",
  "Kenneth Patton",
  "Kahlil Gibran",
  "Flora Whittemore",
  "H. W. Arnold",
  "Eden Phillpotts",
  "Mark Twain",
  "Lin-yutang",
  "Dave Weinbaum",
  "Augustinus Sanctus",
  "Henri-Frederic Amiel",
  "Louisa Alcott",
  "Annie Dillard",
  "Man Ray",
  "Henry Ford",
  "St. Augustine",
  "John De Paola",
  "Lily Tomlin",
  "Martin Fischer",
  "John Adams",
  "Henry David Thoreau",
  "Calvin Coolidge",
  "General Douglas MacArthur",
  "Julius Charles Hare",
  "Buckminster Fuller",
  "Walter Lippmann",
  "Bruce Lee",
  "Jim Beggs",
  "Donald Kircher",
  "Eckhart Tolle",
  "H. Jackson Browne",
  "Marquis Vauvenargues",
  "Charlotte Bronte",
  "Robert Stevenson",
  "Andy Warhol",
  "Pema Chodron",
  "Horace",
  "Morris West",
  "Franklin Roosevelt",
  "Edwin Chapin",
  "Les Brown",
  "Havelock Ellis",
  "John Ruskin",
  "Thomas Hardy",
  "Leonardo Ruiz",
  "Leon Blum",
  "Charles Dickens",
  "Sam Keen",
  "Walt Emerson",
  "John Astin",
  "Henry Moore",
  "Laozi",
  "George Sheehan",
  "Antoine de Saint-Exupery",
  "Marcel Proust",
  "Louise Hay",
  "W. Clement Stone",
  "Robert McKain",
  "John Quincy Adams",
  "William Saroyan",
  "Isaac Asimov",
  "Henry Van Dyke",
  "Naguib Mahfouz",
  "Anthony Robbins",
  "Jane Addams",
  "Thomas Carlyle",
  "M. Scott Peck",
  "Maureen Dowd",
  "Charles Darwin",
  "Christopher Morley",
  "Hannah Arendt",
  "Alan Cohen",
  "Aldous Huxley",
  "Marian Edelman",
  "Sue Patton Thoele",
  "Frank Crane",
  "Kathleen Norris",
  "Anne Bronte",
  "Desiderius Erasmus",
  "Arthur Rubinstein",
  "Louis Pasteur",
  "Rumi",
  "Sogyal Rinpoche",
  "Dennis Kimbro",
  "William Penn",
  "Robert Lynd",
  "Robert Fulghum",
  "Arthur Schopenhauer",
  "Andre Gide",
  "Sai Baba",
  "Tom Lehrer",
  "Alfred Sheinwold",
  "Sri Chinmoy",
  "James Freeman Clarke",
  "Sydney Smith",
  "Mary Kay Ash",
  "Lloyd Jones",
  "Vista Kelly",
  "Ben Stein",
  "Jacob Braude",
  "Vince Lombardi",
  "Oliver Holmes",
  "Nelson Mandela",
  "Robert Anthony",
  "Washington Irving",
  "Anne Frank",
  "Jessamyn West",
  "Charlotte Gilman",
  "Mother Teresa",
  "Margaret Runbeck",
  "James Barrie",
  "Everett Dirksen",
  "Henry Miller",
  "Niels Bohr",
  "Georg Lichtenberg",
  "Charles Schwab",
  "Barbara Baron",
  "Lou Holtz",
  "Charles DeLint",
  "Paavo Nurmi",
  "Tryon Edwards",
  "E. M. Forster",
  "David Seamans",
  "Lucille Ball",
  "Laurence J. Peter",
  "Elizabeth Arden",
  "Nikola Tesla",
  "Leo Aikman",
  "Vernon Cooper",
  "Jack Dixon",
  "G. K. Chesterton",
  "Denis Waitley",
  "Lao-Tzu",
  "Johannes Gaertner",
  "Doug Larson",
  "Charles Lamb",
  "John Muir",
  "William Ward",
  "Michael Jordan",
  "Barack Obama",
  "Ivy Baker Priest",
  "Danielle Ingrum",
  "Old German proverb",
  "Ralph Blum",
  "Walter Cronkite",
  "Chalmers",
  "Robert Louis Stevenson",
  "Henry Thoreau",
  "Joan Didion",
  "Mabel Newcomber",
  "Robert Graves",
  "Frank Wright",
  "Francois de La Rochefoucauld",
  "Margaret Cousins",
  "Catherine Pulsifer",
  "Alfred Tennyson",
  "Margaret Mead",
  "Remez Sasson",
  "David Jordan",
  "Alan Watts",
  "John Steinbeck",
  "Eknath Easwaran",
  "Norman Schwarzkopf",
  "Julie Morgenstern",
  "Laura Teresa Marquez",
  "Harry Kemp",
  "John Kennedy",
  "Henry Longfellow",
  "Daisaku Ikeda",
  "Rene Descartes",
  "Amelia Earhart",
  "Jimmy Dean",
  "George Allen",
  "Joseph Roux",
  "Bernice Reagon",
  "Henri Bergson",
  "David Brinkley",
  "Pierre Auguste Renoir",
  "Bob Newhart",
  "Rita Mae Brown",
  "Lululemon",
  "Kin Hubbard",
  "Mary Morrissey",
  "Leo Buscaglia",
  "Peter Elbow",
  "Heraclitus",
  "Rudolf Arnheim",
  "Channing",
  "Cervantes",
  "Samuel Johnson",
  "Tehyi Hsieh",
  "Japanese proverb",
  "Cicero",
  "Charles Swindoll",
  "Cynthia Ozick",
  "Lena Horne",
  "Tom Peters",
  "Lee Mildon",
  "Shakti Gawain",
  "Walter Anderson",
  "Paul Cezanne",
  "Tom Krause",
  "Frank Tyger",
  "Dorothy Thompson",
  "Shunryu Suzuki",
  "Tomas Eliot",
  "John Dewey",
  "Richard Braunstein",
  "George Orwell",
  "John Petit-Senn",
  "George Eliot",
  "Mary Wollstonecraft",
  "Sheldon Kopp",
  "Satchel Paige",
  "George Bernard Shaw",
  "Billy Wilder",
  "Niccolo Machiavelli",
  "Henry Ward Beecher",
  "James Faust",
  "Hasidic saying",
  "Joseph Campbell",
  "Fannie Hamer",
  "Byron Roberts",
  "Babatunde Olatunji",
  "Tony Blair",
  "Ray Bradbury",
  "Herbert Swope",
  "Ed Cunningham",
  "Angela Schwindt",
  "Orison Marden",
  "Sam Levenson",
  "Doris Mortman",
  "Mohandas Gandhi",
  "Mortimer Adler",
  "Walter Linn",
  "Tenzin Gyatso",
  "Edmund Burke",
  "William Channing",
  "Alphonse Karr",
  "W. H. Auden",
  "Michel de Montaigne",
  "Margaret Laurence",
  "Ajahn Chah",
  "Vincent Lombardi",
  "Jean-Paul Sartre",
  "Elisabeth Kubler-Ross",
  "Anne Lindbergh",
  "Dale Carnegie",
  "Nathaniel Hawthorne",
  "Caroline Myss",
  "William James",
  "Uta Hagen",
  "Victor Frankl",
  "Edward de Bono",
  "Amy Tan",
  "Stephen Covey",
  "Paul Graham",
  "Chuck Norris",
  "Amiel",
  "Amy Bloom",
  "Keshavan Nair",
  "Margaret Smith",
  "Ingrid Bergman",
  "Thornton Wilder",
  "James Oppenheim",
  "Martha Washington",
  "Margaret Bonnano",
  "Goethe",
  "Joe Paterno",
  "Cathy Pulsifer",
  "Bishop Desmond Tutu",
  "Chanakya",
  "Demosthenes",
  "Gail Sheehy",
  "English proverb",
  "John Locke",
  "Soren Kierkegaard",
  "David Eddings",
  "David McCullough",
  "William Blake",
  "Cheng Yen",
  "Euripides",
  "William Sloane Coffin",
  "Andy Rooney",
  "Martin Luther King, Jr.",
  "Paul Tillich",
  "William Burroughs",
  "Alfred Painter",
  "Anne Lamott",
  "Charles Perkhurst",
  "Robert Kennedy",
  "Richard Whately",
  "Marsha Petrie Sue",
  "Alexander Pope",
  "Nietzsche",
  "Brendan Francis",
  "Abraham Maslow",
  "Zig Ziglar",
  "Frances de Sales",
  "Kenji Miyazawa",
  "George Matthew Adams",
  "Robert M. Pirsig",
  "Albert Gray",
  "Grandma Moses",
  "Swedish proverb",
  "Felix Adler",
  "Joseph Joubert",
  "Ella Fitzgerald",
  "C. Pulsifer",
  "Fran Watson",
  "Mary Almanac",
  "Ralph Marston",
  "Lewis Cass",
  "Thomas Paine",
  "Danilo Dolci",
  "Franz Liszt",
  "Corita Kent",
  "Alice Walker",
  "Charles Chesnutt",
  "Elizabeth Kenny",
  "Aesop",
  "Mal Pancoast",
  "Edward Young",
  "Claire Charmont",
  "Sinvyest Tan",
  "Joyce Brothers",
  "Anthony D'Angelo",
  "Gordon Hinckley",
  "Edmond Rostand",
  "Ymber Delecto",
  "Michael Vance",
  "Samuel Taylor Coleridge",
  "Naomi Williams",
  "Frederick Wilcox",
  "Simone Weil",
  "Forrest Gump",
  "Jean Lacordaire",
  "Moliere",
  "Booker Washington",
  "Woody Guthrie",
  "Forrest Church",
  "Coco Chanel",
  "Ambrose Bierce",
  "Etty Hillesum",
  "William Londen",
  "Theodore Roosevelt",
  "William White",
  "Jamie Paolinetti",
  "Eriksson",
  "Joe Namath",
  "Pierre Abelard",
  "John F. Kennedy",
  "Dr. David M. Burns",
  "Wolfgang Amadeus Mozart",
  "H. Bertram Lewis",
  "Saul Alinsky",
  "Charles A. Lindbergh",
  "Robert Brault",
  "John Lubbock",
  "Alfred Adler",
  "Robert Schuller",
  "Stephen Kaggwa",
  "Percy Shelley",
  "Korean proverb",
  "Bertrand Russell",
  "Douglas Adams",
  "Muriel Rukeyser",
  "Will Durant",
  "Lauren Raffo",
  "John Barrymore",
  "Winifred Holtby",
  "Richard Garriott",
  "Harriet Lerner",
  "Doug Horton",
  "Maori proverb",
  "Jack Buck",
  "Whoopi Goldberg",
  "Henry Reed",
  "Pat Riley",
  "Galileo Galilei",
  "Margaret Wheatley",
  "Sarah Breathnach",
  "Lisa Alther",
  "Walter Benjamin",
  "Lama Yeshe",
  "Cardinal Retz",
  "E. E. Cummings",
  "Holmes",
  "Vaclav Havel",
  "Katherine Mansfield",
  "Victoria Holt",
  "Chuang Tzu",
  "Billie Armstrong",
  "Alfred Korzybski",
  "Alfred Whitehead",
  "Charlotte Perkins Gilman",
  "James Yorke",
  "Isocrates",
  "Carl Bard",
  "Robert Orben",
  "Hermann Hesse",
  "Franklin D. Roosevelt",
  "David Bader",
  "Mahummad Ali",
  "David Rockefeller",
  "Cavour",
  "Ellen Parr",
  "James Openheim",
  "Henry Beecher",
  "John Acosta",
  "Moncure Conway",
  "Norman Peale",
  "Alexander the Great",
  "Theodore Rubin",
  "Harriet Tubman",
  "George Santayan",
  "Carlos Castaneda",
  "Dhammapada",
  "Henry James",
  "Colette",
  "William Hazlitt",
  "Geoffrey F. Abert",
  "Philip Breedveld",
  "John Powell",
  "Tim Menchen",
  "Charles Dubois",
  "Stephen Sigmund",
  "Charles R. Swindoll",
  "John Marshall",
  "George Sand",
  "Matt Zotti",
  "Jane Roberts",
  "Norman Cousins",
  "Cadet Maxim",
  "Hausa",
  "Arie de Gues",
  "Paul Boese",
  "Edwin Markham",
  "Robert Southey",
  "Max Planck",
  "Anna Pavlova",
  "Rabindranath Tagore",
  "Edith Wharton",
  "Edna Millay",
  "Cecil B. DeMille",
  "George Shaw",
  "Harry Banks",
  "Colin Powell",
  "Henri Amiel",
  "Betty Friedan",
  "John Simone",
  "Plotinus",
  "Mary Parrish",
  "Henri L. Bergson",
  "Ziggy",
  "Zadok Rabinowitz",
  "William Lyon Phelps",
  "John Holmes",
  "Nora Roberts",
  "Jules Poincare",
  "Carla Gordon",
  "Edward Ericson",
  "Linda Hogan",
  "May Sarton",
  "Rachel Carson",
  "Ernest Hemingway",
  "Hannah Senesh",
  "Harry Burchell Mathews",
  "Michael Burke",
  "Edgar Allan Poe",
  "Ben Sweetland",
  "John Updike",
  "Carl Sagan",
  "Jawaharlal Nehru",
  "Elizabeth Montagu",
  "William Scolavino",
  "Rabbi Hillel",
  "Audre Lorde",
  "Alexis Carrel",
  "James Pence",
  "Agatha Christie",
  "Dale Earnhardt",
  "Robert C. Solomon",
  "Sam Rayburn",
  "Jonathan Swift",
  "Margaret Fuller",
  "Will Rogers",
  "Lee Womack",
  "William Menninger",
  "Eddie Cantor",
  "Francoise de Motteville",
  "Jim Bishop",
  "Thomas Kempis",
  "Abernathy",
  "Christian Bovee",
  "Mary Pickford",
  "Robert Pirsig",
  "Doris Day",
  "Richard Needham",
  "Harriet Woods",
  "Philip Sidney",
  "Anne Bradstreet",
  "Marianne Williamson",
  "Benjamin Haydon",
  "Ella Wilcox",
  "John Junor",
  "Barbara De Angelis",
  "Lazurus Long",
  "Theodore H. White",
  "Melody Beattie",
  "Harold Nicolson",
  "Rodin",
  "Tom Jackson",
];
export default authors;
